---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "miesportal.sqlserverFullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miesportal.labels" . | nindent 4 }}
spec:  
  replicas: 1
  selector:
    matchLabels:
      {{- include "miesportal.selectorLabels" . | nindent 6 }}
      {{- with .Values.sqlserver.podLabels }}      
        {{- toYaml . | nindent 6 }}
      {{- end }}
  serviceName: {{ include "miesportal.sqlserverFullName" . }}
  template:
    metadata:
      labels:
        {{- include "miesportal.selectorLabels" . | nindent 8 }}
        {{- with .Values.sqlserver.podLabels }}      
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: {{ .Values.sqlserver.password }}
        image: mcr.microsoft.com/mssql/server:2019-CU20-ubuntu-20.04
        imagePullPolicy: {{ .Values.sqlserver.image.pullPolicy }}
        name: sqlserver
        ports:
        - containerPort: 1433
          protocol: TCP
        volumeMounts:
        - mountPath: /var/opt/mssql/data
          name: efs-sqlsystem
      volumes:
      - name: efs-sqlsystem
        persistentVolumeClaim:
          claimName: {{ .Values.sqlserver.pvc.id }}-{{ include "miesportal.fullname" . }}
