---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "miesportal.sqlserverFullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miesportal.labels" . | nindent 4 }}
spec:  
  ports:
    - port: 1433      
      protocol: TCP
  selector:
    {{- include "miesportal.selectorLabels" . | nindent 4 }}
    {{- with .Values.sqlserver.podLabels }}      
      {{- toYaml . | nindent 4 }}
    {{- end }}