---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "miesportal.webapiFullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miesportal.labels" . | nindent 4 }}
spec:  
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "miesportal.selectorLabels" . | nindent 4 }}
    {{- with .Values.webapi.podLabels }}      
      {{- toYaml . | nindent 4 }}
    {{- end }}