---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miesportal.webserviceFullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miesportal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "miesportal.selectorLabels" . | nindent 6 }}
      {{- with .Values.webservice.podLabels }}      
        {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:      
      labels:
        {{- include "miesportal.selectorLabels" . | nindent 8 }}
        {{- with .Values.webservice.podLabels }}      
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        {{- include "miesportal.secretsloadedprobeContainer" . | nindent 8 }}     
      containers:
        - name: {{ .Values.webservice.id }}          
          image: "{{ .Values.repository }}/{{ .Values.webservice.id }}:{{ .Values.webservice.image.tag }}"
          imagePullPolicy: {{ .Values.webservice.image.pullPolicy }}
          volumeMounts:
          - name: appsettings
            subPath: "appsettings.Production.json"
            mountPath: "/app/appsettings.json"
          envFrom:
          - secretRef:
              name: {{ include "miesportal.mssqlconnectionstringsecretFullName" . }}
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_URLS
            value: "http://*:44367" 
          ports:
            - name: http
              containerPort: 44367
              protocol: TCP          
          resources:
            {{- toYaml .Values.webservice.resources | nindent 12 }}
      volumes:
      - name: appsettings
        configMap:
          name: {{ include "miesportal.appsettingsFullName" . }}
      - name: secretsloadedprobe
        configMap:
          name: {{ include "miesportal.secretsloadedprobeFullName" . }}
          defaultMode: 0744
      - name: externalsecrets
        secret:
          secretName: {{ include "miesportal.mssqlconnectionstringsecretFullName" . }}