---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miesportal.workerserviceFullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miesportal.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "miesportal.selectorLabels" . | nindent 6 }}
      {{- with .Values.workerservice.podLabels }}      
        {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:      
      labels:
        {{- include "miesportal.selectorLabels" . | nindent 8 }}
        {{- with .Values.workerservice.podLabels }}      
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        {{- include "miesportal.secretsloadedprobeContainer" . | nindent 8 }}     
      containers:
        - name: {{ .Values.workerservice.id }}          
          image: "{{ .Values.repository }}/{{ .Values.workerservice.id }}:{{ .Values.workerservice.image.tag }}"
          imagePullPolicy: {{ .Values.workerservice.image.pullPolicy }}
          volumeMounts:
          - name: appsettings
            subPath: "appsettings.Production.json"
            mountPath: "/app/appsettings.json"
          envFrom:
          - secretRef:
              name: {{ include "miesportal.mssqlconnectionstringsecretFullName" . }}  
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          resources:
            {{- toYaml .Values.workerservice.resources | nindent 12 }}
      volumes:
      - name: appsettings
        configMap:
          name: {{ include "miesportal.appsettingsFullName" . }}
      - name: secretsloadedprobe
        configMap:
          name: {{ include "miesportal.secretsloadedprobeFullName" . }}
          defaultMode: 0744
      - name: externalsecrets
        secret:
          secretName: {{ include "miesportal.mssqlconnectionstringsecretFullName" . }}