apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miesportal.secretsloadedprobeFullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miesportal.labels" . | nindent 4 }}
data:
  checkSecret.sh: |-
    {{- include "miesportal.checkSecret.sh" . | nindent 4 }}