{{- $role := printf "arn:aws:iam::%s:role/external-secrets.io" .Values.accountId -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "miesportal.externalsecretsFullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miesportal.labels" . | nindent 4 }}  
  annotations:
    eks.amazonaws.com/role-arn: {{ $role }}