{{- $aws_secretmanager_key := printf "k8/cluster/MIES_PORTAL/%s/SQLSERVERCredentials" .Values.mesh -}}
{{- $portal_connection := printf "%s_%s_svc_1433.mesh,80;User Id={{ .MIESPORTAL_DB_USER }};Password={{ .MIESPORTAL_DB_PWD }};Database=NECMSSDB;TrustServerCertificate=True" (include "miesportal.sqlserverFullName" .) .Release.Namespace -}}
{{- $portal_connection_string := printf "Server=%s" $portal_connection -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "miesportal.externalsecretsFullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miesportal.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "miesportal.mssqlconnectionstringsecretFullName" . }}
    creationPolicy: "Owner"
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        MIESPORTAL_PORTALCONNECTIONSTRING: {{ $portal_connection_string }}
  data:
  - secretKey: MIESPORTAL_DB_USER
    remoteRef:
      key: {{ $aws_secretmanager_key }}
      property: MIESPORTAL_DB_USER
  - secretKey: MIESPORTAL_DB_PWD
    remoteRef:
      key: {{ $aws_secretmanager_key }}
      property: MIESPORTAL_DB_PWD